### ISSUE TITLE
Fractional year value in the return simulation crashes the site

### ISSUE THREAD

**Issue by Unsttopabull** [antonnell/yearn-finance#13]
Steps to reproduce:

-  Enter 0.5 into the "years" field on gains simulation
- The site will crash with only a white screen and "An unexpected error has occurred" displayed.

**Comment by antonnell** [comment]
@patcito Could you have a look at this please?

**Comment by patcito** [comment]
@antonnell will do

**Comment by patcito** [comment]
Should be fixed in #14 you can test here @Unsttopabull https://yearn-finance-1-hyzk1m2sc-patcito.vercel.app/invest/0x5f18C75AbDAe578b483E5F43f12a39cF75b973a9
