### ISSUE TITLE
feat: Add user defined slippage tolerance on zaps

### ISSUE THREAD

**Issue by antonnell** [antonnell/yearn-finance#21]
Allow the user to input their own slippage tolerance.
Default selection of 1%/2%/3%/Custom

**Comment by patcito** [comment]
ok, I'll give it a try

**Comment by patcito** [comment]
Deployed here https://yearn-finance-1-git-custom-zapper-slippage-patcito.vercel.app/ 

See #28

**Comment by antonnell** [comment]
Looks good, I just fixed one bug where zapperSlippage was not defined. Should have it deployed later.
