### ISSUE TITLE
Option to display native token values as well as fiat?

### ISSUE THREAD

**Issue by davidfloyd91** [antonnell/yearn-finance#33]
It might be nice to be able to see v2 vault balances denominated in `want` instead of dollars. Personally I find the `crvSTETH` value of that vault more interesting than the dollar equivalent, since the later fluctuates more due to price changes than harvests.

This could be a toggle like the night/day mode toggle, or something else.

I'm happy to implement this feature, assuming it's wanted and doesn't already exist. (I miss things.)

**Comment by antonnell** [comment]
You are welcome to make that change.

A couple of options for how to implement:

1) Toggle button between native currency and Dollar
2) Multiple values on each card for the balance, stacked on top of each other. On the table view, you can just add another column.
3) A tooltip on hover displaying the native value 

I think I would be leaning towards option 2.
Something like this:
![image](https://user-images.githubusercontent.com/38530524/116375502-a029c580-a80f-11eb-9100-e0271165b08b.png)

Let me know your thoughts?

**Comment by davidfloyd91** [comment]
option 2 looks good. love an excuse not to mess with local storage and state
