### ISSUE TITLE
bug: crvSTETH v2 vault displays incorrect unit in balance

### ISSUE THREAD

**Issue by davidfloyd91** [antonnell/yearn-finance#8]
the crvSTETH v2 vault displays the user's ether balance, but with a dollar sign in front of it. in other words, the amount hasn't been converted to dollars, just presented as if it were in dollars.

i have 1000000.58 ether, not $1000000.58 worth of ether (i've obviously edited the figure to avoid disclosing my real balance, which is nine trillion ether):

<img width="458" alt="Screen Shot 2021-03-21 at 11 48 08 PM" src="https://user-images.githubusercontent.com/31059979/111938266-f92f6c80-8a9f-11eb-8e81-cc0b033639b1.png">

apologies if this isn't the place to post this issue, happy to move it to a more appropriate place if you point me there. or expand/reformat it.

and happy to submit a pr to fix this if y'all like.

**Comment by patcito** [comment]
That's because crvSTETH is not listed on coingecko so the api call returns an empty object, this is the exact call https://api.coingecko.com/api/v3/simple/token_price/ethereum?contract_addresses=0x06325440D014e39736583c165C2963BA99fAf14E&vs_currencies=usd

For Dai for example, it returns the price as expected https://api.coingecko.com/api/v3/simple/token_price/ethereum?contract_addresses=0x6B175474E89094C44Da98b954EedeAC495271d0F&vs_currencies=usd&name

Not sure where we could fetch the price of crvSTETH, maybe just fetch the price of STETH instead as it is on coingecko?

**Comment by antonnell** [comment]
Yea, I've been aware of it for a while, I've just not had the time to get to it.
Eventually I want to replace the coingecko price lookup with an on-chain price oracle lookup. (uniquote, chainlink etc)

STETH's price won't be the same as crvSTETH, so it's not the best solution. It will be more accurate than what there currently is, but I think a better short term solution is to have crvSTETH listed on coingecko. I believe there is a process that coingecko has that can be followed to get a token listed on there.

Would either of you like to investigate that and get it started? Not sure if there are any other assets that would also need to go through the process.

**Comment by patcito** [comment]
I think I found a workaround, I'll try to push something by tonight.

**Comment by patcito** [comment]
Ok, I pushed a fix in #9 , it's deployed here if you want to test https://yearn-finance-1-667d2kmc1-patcito.vercel.app/ Not sure about growth numbers though but balance looks better.

**Comment by davidfloyd91** [comment]
looks great @patcito thanks

**Comment by 3cl1ps** [comment]
hey, thanks for the fix. 
the filter on tip of the column (croissant/decroissant) is not working.

**Comment by patcito** [comment]
> the filter on top of the column (croissant/decroissant) is not working.

which column?

**Comment by 3cl1ps** [comment]
![image](https://user-images.githubusercontent.com/2938587/112368750-b22dbb00-8cdb-11eb-8554-e15b758dccb4.png)
i meant ordering on invested balance.

**Comment by patcito** [comment]
@3cl1ps ok, this is because it's sorting by the amount of token instead of its value in dollar so if you have $100 usdt it will show before eg 12 crvSTETH. I'll try to fix that.

**Comment by patcito** [comment]
@3cl1ps I pushed a fix here, could you give it a try please? https://yearn-finance-1-1bo9vvo0k-patcito.vercel.app/

**Comment by 3cl1ps** [comment]
working, thanks

Le mer. 24 mars 2021 à 21:05, Patrick Aljord ***@***.***> a
écrit :

**Comment by antonnell** [comment]
Version 1.1.3 deployed to https://yearn.fi/

If you are happy with the changes @davidfloyd91 then you can close the issue.

**Comment by antonnell** [comment]
Closing because I assume it is fixed up to their standard.

**Comment by davidfloyd91** [comment]
sorry for disappearing. lgtm
